language: java
jdk: oraclejdk11
sudo: false
cache:
  directories:
    - $home/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    CODECOV_TOKEN='5abf343f-7c0f-4ac4-8ec5-0cfac4b33413'